config/routes.rb
# Rails.application.routes.draw do
#   resources :events do
#     member do
#       get 'yes_response', to: 'events#yes_response'
#       get 'no_response', to: 'events#no_response'
#       get 'yes_response_series', to: 'events#yes_response_series'
#       get 'no_response_series', to: 'events#no_response_series'
#     end
#     resource :event_info
#   end

#   root 'signin#new'
#   get 'static_pages/home'
#   get 'static_pages/help'
  
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root 'static_pages#main'
#   get 'signin', to: 'signin#new'

#   # root :to => redirect('/static_pages/home')
#   get 'home' => 'static_pages#home'
#   get 'series' => 'events#series_event'
#   get 'newEvents' => 'events#new'
#   get 'eventsList' => 'events#event_status'
#   get 'peopleList' => 'people_list#people_list'
#   get 'eventdashboard' => 'events#eventdashboard'
#   get 'signup' => 'users#new'

#   get 'invite_attendees/:id' => 'events#invite_attendees', as: "invite_attendees"
#   get 'send_reminders_to_attendees/:id' => 'events#send_reminders_to_attendees', as: 'send_reminders_to_attendees'
#   # get '/login' => 'login#new'
#   # post '/login' => 'login#create'
#   # get '/signin' => 'Signin#new'
#   # post '/signin' => 'Signin#create'
#   get '/signin', to: 'signin#new'
#   post '/signin', to: 'signin#create'

#   #get 'events/:id/email_invitation' => 'events#email_invitation', as: :email_invitation


#   #get 'eventsList' => 'events#index'

#   #for login
#   # post '/check_login', to: 'login_controller#check_login'

# end






Rails.application.routes.draw do
  # Events routes
  resources :events do
    member do
      get 'yes_response', to: 'events#yes_response'
      get 'no_response', to: 'events#no_response'
      get 'yes_response_series', to: 'events#yes_response_series'
      get 'no_response_series', to: 'events#no_response_series'
    end
    resource :event_info
  end

  # Static pages routes
  get 'static_pages/home'
  get 'static_pages/help'

  # Sign-in routes
  get 'signin', to: 'signin#new'
  post 'signin', to: 'signin#create'

  # Sign-up route
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  # Home route
  root 'signin#new'

  # Other custom routes
  get 'home', to: 'static_pages#home'
  get 'series', to: 'events#series_event'
  get 'newEvents', to: 'events#new'
  get 'eventsList', to: 'events#event_status'
  get 'peopleList', to: 'people_list#people_list'
  get 'eventdashboard', to: 'events#eventdashboard'
  get 'invite_attendees/:id', to: 'events#invite_attendees', as: 'invite_attendees'
  get 'send_reminders_to_attendees/:id', to: 'events#send_reminders_to_attendees', as: 'send_reminders_to_attendees'
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendee_infos
    has_many :time_slots
    accepts_nested_attributes_for :time_slots, allow_destroy: true
    has_one :event_info 
    has_one_attached :csv_file
end

app/controllers/events_controller.rb
require 'csv'
require 'roo'
require 'securerandom'


class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
    # Create EventInfothat corresponds to Event
    @event_info = EventInfo.new
  end

  # GET /events/1/edit
  def edit
    if @event.time_slots.present?
      render "series_event"
    end
  end

  # POST /events or /events.json
  def create
    name = event_params[:name]
    venue = event_params[:venue]
    date = event_params[:date]
    csv_file = event_params[:csv_file]
    start_time = event_params[:start_time]
    end_time = event_params[:end_time]
    max_capacity = event_params[:max_capacity]


    if date.nil?
      date = Time.now
    end

    @event = Event.new(
      name:       name
    )
    @event_info = EventInfo.new(
      name:         name,
      venue:        venue,
      date:         date,
      start_time:   start_time,
      end_time:     end_time,
      max_capacity: max_capacity
    )

    if csv_file.present? && File.extname(csv_file.path) == '.csv'
      @event.csv_file.attach(csv_file)
      # Parse the CSV data
      csv_data = csv_file.read
      parsed_data = CSV.parse(csv_data, headers: true)
    elsif csv_file.present? && File.extname(csv_file.path) == '.xlsx'
      excel_data = csv_file.read
      workbook = Roo::Excelx.new(StringIO.new(excel_data))
      worksheet = workbook.sheet(0) # Assuming the data is in the first sheet
      headers = worksheet.row(1) # Assuming headers are in the first row
      parsed_data = []
      (2..worksheet.last_row).each do |i| # Start from the second row
        row = Hash[[headers, worksheet.row(i)].transpose]
        parsed_data << row
      end
    end

    # NOTE: @event.id does not exist until the record is SAVED

    respond_to do |format|
      if @event.save

        # Create time_slot data if applicable 
        @event.update(event_params.extract!(:time_slots_attributes))

        # Save the other events reference to the event
        # ---------------------- Make this a separate function ------------------- #
        if parsed_data.nil?
          # Handle the case when parsed_data is nil
          puts "parsed_data is nil"
        else
          if parsed_data.empty?
            # Handle the case when parsed_data is an empty array
            puts "parsed_data is empty"
          else
            parsed_data.each do |row|
              email = row["Email"]
              priority = row["Priority"]
        
              @attendee = AttendeeInfo.new(
                email: email,
                event_id: @event.id,
                email_token: SecureRandom.uuid,
                priority: priority,
              )
              unless @attendee.save
                puts "Validation errors: #{@attendee.errors.full_messages}"
              end
            end
          end
        end
        # ----------------------------------------------------------------------- #
        @event_info.event_id = @event.id
  
        if @event_info.save
          format.html do
            redirect_to event_url(@event), notice: 'Event was successfully created.'
          end
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    name = event_params[:name]
    venue = event_params[:venue]
    date = event_params[:date]
    start_time = event_params[:start_time]
    end_time = event_params[:end_time]
    max_capacity = event_params[:max_capacity]
    csv_file = event_params[:csv_file]

    event_info = @event.event_info

    respond_to do |format|
      if @event.time_slots.present? && @event.update(event_params.extract!(:name, :time_slots_attributes)) && event_info.update(name: name, venue: venue)
          format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
      elsif @event.update(name: name) && event_info.update(event_params.except(:csv_file, :time_slots))
          format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def event_status
    @events = Event.all
  end

  def yes_response_series
    @event = Event.find(params[:id])
    @time_slot = TimeSlot.find(params[:time_slot])
    @attendee_info = @event.attendee_infos.find_by(email_token: params[:token])

    # If any of the data doesn't exist then return
    if !@event.present? || !@time_slot.present? || !@attendee_info.present?
      redirect_to event_url(@event), notice: 'Invalid Response Params'
      return
    else
      
    end

    # Does the time_slot already belong to someone?
    if !@time_slot.attendee_info.nil?
      redirect_to event_url(@event), notice: 'Time-slot has already been selected, Please select another one'
      return
    end

    # Does the attendee already have a time_slot? We need to decide what to do about this but for now deny it
    if @attendee_info.time_slot.present?
      redirect_to event_url(@event), notice: 'You have already selected a time-slot, Please contact admin to change selected time'
      return
    end

    # Good path, time_slot doesn't belong to anyone and attendee doesn't already have a time_slot they have selected
    @attendee_info.update!(is_attending: "yes")
    @time_slot.update!(attendee_info_id: @attendee_info.id)

    redirect_to event_url(@event), notice: 'Your response has been recorded'
  end

  def yes_response
    @event = Event.find(params[:id])
    @attendee_info = @event.attendee_infos.find_by(email_token: params[:token])

    if @event.present? && @attendee_info.present?
      @attendee_info.update(is_attending: "yes")
    end
    
    redirect_to event_url(@event), notice: 'Your response has been recorded'
  end

  def no_response
    @event = Event.find(params[:id])
    @attendee_info = @event.attendee_infos.find_by(email_token: params[:token])

    if @event.present? && @attendee_info.present?
      @attendee_info.update(is_attending: "no")
    end

    # Find the next attendee who hasn't responded yet and is not at max capacity
    next_attendee = @event.attendee_infos.where(email_sent: false).where.not(id: attendees_at_or_over_capacity).first

    if next_attendee.present?
      EventRemainderMailer.with(email: next_attendee.email, token: next_attendee.email_token, event: @event).reminder_email.deliver
      next_attendee.update(email_sent: true)
      next_attendee.update(email_sent_time: DateTime.now)
    end
    redirect_to event_url(@event), notice: 'Your response has been recorded'
  end

  def attendees_at_or_over_capacity
    @event = Event.find(params[:id])
    @event_info = @event.event_info
    max_capacity = @event_info.max_capacity
    attendees_at_capacity = @event.attendee_infos.where(is_attending: ["yes", "no"], email_sent: true).limit(max_capacity)
    attendees_at_capacity
  end

  

  def invite_attendees
    @event = Event.find(params[:id])
    @event_info = @event.event_info

    yes_attendees = @event.attendee_infos.where(is_attending: "yes")

    if @event_info.max_capacity.present? && @event_info.max_capacity != yes_attendees.count

      attendees_to_invite = @event.attendee_infos.where(email_sent: false).limit(@event_info.max_capacity)
      attendees_to_invite.each do |attendee|
        EventRemainderMailer.with(email: attendee.email, token: attendee.email_token, event: @event).reminder_email.deliver
        attendee.update(email_sent: true)
        attendee.update(email_sent_time: DateTime.now)
      end
    elsif !@event_info.max_capacity.present?
      @event.attendee_infos.where(email_sent: false).each do |attendee|
        EventRemainderMailer.with(email: attendee.email, token: attendee.email_token, event: @event).reminder_email.deliver
        attendee.update(email_sent: true)
        attendee.update(email_sent_time: DateTime.now)
      end
    end
    redirect_to eventsList_path
  end


  def send_reminders_to_attendees

    @event = Event.find(params[:id])
    @event_info = @event.event_info

    # Find attendees who responded "yes"
    yes_attendees = @event.attendee_infos.where(is_attending: "yes")

    # Send emails to those attendees who have already responded "yes"
    yes_attendees.each do |attendee|
      EventRemainderMailer.with(email: attendee.email, token: attendee.email_token, event: @event).event_reminder.deliver
    end
    redirect_to eventsList_path
  end

  def series_event
    @event = Event.new
    @event_info = EventInfo.new
    @event.time_slots.build
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :venue, :date, :start_time, :end_time, :max_capacity, :csv_file, time_slots_attributes: [:id, :date, :start_time, :end_time, :_destroy])

  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Details</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body, html {
            height: 100%;
            margin: 0;
            font-family: 'Arial', sans-serif;
            background-color: #000;
            color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
        }

        .event-card {
            //background-color: #333;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            width: auto;
        }

        .event-header {
            padding: 30px 20px;
            color: white;
            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
            font-size: 2em;
            font-weight: bold;
            letter-spacing: 2px;
        }

        .event-content {
            padding: 30px 20px;
        }

        .gradient-btn {
            background: #555;
            border: none;
            color: white;
            padding: 12px 30px;
            border-radius: 30px;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
            transition: all 0.3s;
        }

        .gradient-btn:hover {
            background: #666;
            box-shadow: 0 5px 20px rgba(0, 0, 0, 0.4);
            transform: translateY(-2px);
        }

        .event-row {
            display: flex;
            justify-content: center;
            margin-bottom: 10px;
        }

        .event-col {
            flex: 1;
            padding: 0 10px;
        }
    </style>
</head>
<body>
    <div class="event-card">
        <div class="event-header">
            <h1>Event Details</h1>
        </div>
        <div class="event-content">
            <div id="<%= dom_id event %>">
                <div class="event-row">
                    <h3 class="event-col"><strong>Name:</strong> <%= event.event_info.name %></h3>    
                    <h3 class="event-col"><strong>Venue:</strong> <%= event.event_info.venue %></h3>
                </div>
                <div class="event-row">
                    <h3 class="event-col"><strong>Date:</strong> <%= event.event_info.date %></h3>
                    <h3 class="event-col"><strong>Max Capacity:</strong> <%= event.event_info.max_capacity %></h3>
                </div>
                <div class="event-row">
                    <% if event.time_slots.present? %>
                        <h3 class="event-col"><strong>Time Slots:</strong></h3>
                        <% event.time_slots.each do |time_slot| %>
                            <h3 class="event-col">
                                <strong>Date:</strong>
                                <%= time_slot.date %>

                                <strong>Start Time:</strong>
                                <%= time_slot.start_time.strftime("%I:%M %p") %>

                                <strong>End Time:</strong>
                                <%= time_slot.end_time.strftime("%I:%M %p") %>
                            </h3>
                        <% end %>
                    <% else %>
                        <h3 class="event-col">
                            <strong>Start Time:</strong>
                            <% if event.event_info.start_time.present? %>
                                <%= event.event_info.start_time.strftime("%I:%M %p") %>
                            <% else %>
                                No data available.
                            <% end %>
                        </h3>
                        <h3 class="event-col">
                            <strong>End Time:</strong>
                            <% if event.event_info.end_time.present? %>
                                <%= event.event_info.end_time.strftime("%I:%M %p") %>
                            <% else %>
                                No data available.
                            <% end %>
                        </h3>
                    <% end %>
                </div>
                <h3 align="center">
                    <% if @event.csv_file.attached? %>
                        <p>
                            <strong>CSV File:</strong>
                            <%= link_to @event.csv_file.filename, rails_blob_path(@event.csv_file) %>
                        </p>
                    <% end %>
                </h3>
                <div>
                    <%= button_to "Add to Google Calendar", create_event_path(event), method: :post, class: "gradient-btn", remote: true %>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/views/events/_time_slot_fields.html.erb
<!-- app/views/events/_time_slot_fields.html.erb -->


<%= f.label "Date" %>
<%= f.date_field :date, class:"form-input", required: true %>

<%= f.label "Start Time" %>
<%= f.time_field :start_time, class:"form-input", required: true%>

<%= f.label "End Time" %>
<%= f.time_field :end_time, class:"form-input", required: true %>

app/views/events/edit.html.erb
<!DOCTYPE html>
<html>

<head>

    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    
    <style>
    body {
        background-color: #e2c9be;
        background-image: #666
        background-size: cover;
        background-repeat: no-repeat;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        font-family: 'Arial', sans-serif;
    }

    .event-card {
        background-color: rgba(255, 255, 255, 0.9);
        box-shadow: 0 10px 25px rgba(0, 0, 0, 0.08);
        border-radius: 15px;
        overflow: hidden;
        transition: transform 0.3s;
    }

    .event-card:hover {
        transform: translateY(-10px);
    }

    .gradient-btn {
        background: #555;
        border: none;
        color: black;
        padding: 12px 30px;
        border-radius: 30px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
        transition: all 0.3s;
    }

    .gradient-btn:hover {
        background: #666;
        box-shadow: 0 5px 20px rgba(0, 0, 0, 0.4);
        transform: translateY(-2px);
    }

    .event-header {
        padding: 30px 20px;
        background-color: #666;
        color: black;
        border-bottom: 1px solid rgba(0, 0, 0, 0.1);
        text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
        font-size: 2em;
        font-weight: bold;
        letter-spacing: 2px;
    }

    .event-content {
        padding: 30px 20px;
    }

    .highlight-text {
        color: rgb(8, 92, 120);
        padding: 5px 10px;
        border-radius: 10px;
        font-size: 1.5em;
        font-weight: bold;
    }

</style>
</head>

<body>
<div class="event-content">
<h3 align = "center">Edit Event</h3>

<%= render "form", event: @event %>

<br>
    
<div>
  <%= link_to "Back to events", events_path, class: "gradient-btn", align: "center", onclick: "history.back()" %>
</div>
</div>
</body>
    

app/views/events/event_status.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <style>
        body, html {
            margin: 0;
            padding: 0;
            font-family: 'Arial', sans-serif;
            background-color: #000; /* Black background for the whole page */
            color: #fff; /* White text color for better contrast */
            display: flex;
            flex-direction: column; /* Arrange content vertically */
            align-items: center;
            text-align: center;
        }

        .event-card {
            background-color: #333; /* Dark background for the card */
            padding: 20px;
            border-radius: 10px; /* Rounded corners for the card */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Subtle shadow for depth */
            width: auto; /* Width adjusted to content */
            margin-bottom: 15px; /* Space between cards */
        }

        .event-header {
            padding: 20px;
            background-color: #555; /* Dark background for the header */
            color: #fff; /* White text for the header */
            border-bottom: 1px solid #666; /* Slightly lighter border color */
            font-size: 1.5em;
            font-weight: bold;
            letter-spacing: 1px;
            cursor: pointer; /* Make the event name clickable */
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .event-content {
            background-color: #555; /* Darker background for content */
            color: #fff; /* White text color */
            display: none; /* Hide the event details by default */
            padding: 20px; /* Adjust padding for better formatting */
        }

        .gradient-btn {
            background-color: #555; /* Button background */
            border: none;
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            transition: all 0.3s;
        }

        .gradient-btn:hover {
            background-color: #666; /* Slightly lighter on hover */
            cursor: pointer; /* Change cursor to pointer */
            transform: translateY(-2px); /* Moves button up slightly on hover */
        }

        .transparent-btn {
            background-color: transparent;
            border: none;
            color: #bbb; /* Lighter text color */
        }

        .transparent-btn:hover {
            color: #fff; /* White color on hover */
        }

        .list-unstyled {
            padding-left: 0;
            list-style: none;
        }

        .attendee {
            margin-bottom: 10px;
        }

        /* Additional padding for the header */
        .dashboard-header {
            padding-bottom: 20px;
        }

    </style>
</head>

<body>
    <% if flash[:notice].present? %>
    <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
    </div>
    <% elsif flash[:alert].present? %>
    <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
    </div>
    <% end %>
    <div class="event-dashboard">
        <div class="dashboard-header">
            <h1>Event Dashboard</h1>
            <div>
                <%= link_to "Back to Home", home_path, class: "gradient-btn" %>
            </div>
        </div>
        
        <ul>
            <% @events.each do |event| %>
                <% attending_count = 0 %>
                <% not_attending_count = 0 %>
                <li class="event-card">
                    <div class="event-header" onclick="toggleEventContent('<%= event.id %>')">
                        <h3><%= event.name %></h3>
                        <div class="event-actions">
                            <%= link_to edit_event_path(event),  class: "btn transparent-btn", role: "button" do %>
                                <i class="fas fa-pencil-alt"></i>
                            <% end %>
                            <%= button_to event, method: :delete, class: "btn transparent-btn", role: "button", onclick:"return confirm('Are you sure?')" do %>
                                <i class="fas fa-trash-alt"></i>
                            <% end %>
                        </div>
                    </div>                    
                    <div id="event-content-<%= event.id %>" class="event-content">
                        <h2>Event Details:</h2>
                        <div>
                            <h3> Date: <%= event.event_info&.date&.strftime('%A, %d %b %Y') %></h3>
                        </div>
                        <div>
                            <h3>Location: <%= event.event_info&.venue %></h3>
                        </div>
                        <div>
                            <% if event.time_slots.present? %>
                                <h3 class="event-col"><strong>Time Slots:</strong></h3>
                                <% event.time_slots.each do |time_slot| %>
                                    <h3 class="event-col">
                                        <%= %>

                                        <%= time_slot.start_time.strftime("%I:%M %p") + " - " + time_slot.end_time.strftime("%I:%M %p") +  "  " + time_slot.date.strftime("%m-%d-%y") %>
                                    </h3>
                                <% end %>
                            <% else %>
                                <h3>Time: <%= event.event_info&.start_time&.strftime('%I:%M %p') + " - " + event.event_info&.end_time&.strftime('%I:%M %p')%></h3>
                            <% end %>
                        </div>
                        <br> <!-- Line break for spacing -->
                        <div>
                            <h3>Yes/No Ratio: <span id="yes-count-<%= event.id %>">0</span> / <span id="no-count-<%= event.id %>">0</span></h3>
                        </div>
                        <div>
                            <% if event.event_info.max_capacity.present? %>
                                <h3>Max Capacity: <%= event.event_info&.max_capacity %></h3>
                            <% end %>
                        </div>
                        <br> <!-- Line break for spacing -->
                        <div>
                            <h3>Send Emails: <%= link_to 'Send Emails', invite_attendees_path(event) %></h3>
                        </div>
                        <div>
                            <h3>Send Reminder Email: <%= link_to 'Send Reminder Email', send_reminders_to_attendees_path(event) %></h3>
                        </div>
                        <h2>Attendees:</h2>
                        <ul class="list-unstyled">
                            <% event.attendee_infos.each do |attendee_info| %>
                                <li class="attendee">
                                    <strong><%= attendee_info&.name %></strong> -
                                    Email: <%= attendee_info&.email %><br>
                                    Status: <%= attendee_info&.is_attending == "yes" ? '<span class="text-success status">Attending</span>'.html_safe : (attendee_info&.is_attending == "no" ? '<span class="text-danger status">Not Attending</span>'.html_safe : '<span class="text-warning status">Pending</span>'.html_safe) %><br>
                                    <% if attendee_info&.is_attending == "yes" %>
                                        <% attending_count += 1 %>
                                    <% else %>
                                        <% not_attending_count += 1 %>
                                    <% end %>
                                    <% if attendee_info.time_slot.present? %>
                                        Time Slot Selected: <%= attendee_info.time_slot.start_time.strftime("%I:%M %p") + " - " + attendee_info.time_slot.end_time.strftime("%I:%M %p") +  "  " + attendee_info.time_slot.date.strftime("%m-%d-%y") %>
                                    <% end %>
                                </li>
                            <% end %>
                        </ul>
                        <div>
                            <%= button_to "Add to Google Calendar", create_event_path(event), method: :post, class: "gradient-btn", remote: true %>
                        </div>
                    </div>
                </li>
                <br> <!-- Line break for each event -->
            <% end %>
        </ul>
    </div>

    <script>
        function toggleEventContent(eventId) {
            var eventContent = document.getElementById("event-content-" + eventId);
            if (eventContent.style.display === "none" || eventContent.style.display === "") {
                eventContent.style.display = "block";
                var attendees = document.querySelectorAll("#event-content-" + eventId + " .attendee");
                var attendingCount = 0;
                var notAttendingCount = 0;
                attendees.forEach(function (attendee) {
                    var status = attendee.querySelector(".status").textContent.trim();
                    if (status === 'Attending') {
                        attendingCount++;
                    } else if (status === 'Not Attending') {
                        notAttendingCount++;
                    }
                });
                document.getElementById("yes-count-" + eventId).textContent = attendingCount;
                document.getElementById("no-count-" + eventId).textContent = notAttendingCount;
            } else {
                eventContent.style.display = "none";
            }
        }
    </script>
</body>

</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
   <head>
      <!-- Bootstrap CSS -->
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
      <style>
         body {
         background-color: #e2c9be;
         background-image: 000;
         background-size: cover;
         background-repeat: no-repeat;
         height: 100vh;
         display: flex;
         align-items: center;
         justify-content: center;
         font-family: 'Arial', sans-serif;
         }
         .event-content {
         padding: 30px 20px;
         }
         .button-wrapper {
         text-align: center;
         margin-top: 30px; 
         }
         .gradient-btn {
         background: #555
         border: none;
         color: white;
         padding: 12px 30px;
         border-radius: 30px;
         box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
         }
         .event-header {
         padding: 30px 20px;
         background-color: #4CAF50;
         color: white;
         border-bottom: 1px solid rgba(0, 0, 0, 0.1);
         text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
         font-size: 2em;
         font-weight: bold;
         letter-spacing: 2px;
         }
         .event-content {
         padding: 30px 20px;
         }
         .highlight-text {
         color: rgb(8, 92, 120);
         padding: 5px 10px;
         border-radius: 10px;
         font-size: 1.5em;
         font-weight: bold;
         }

      </style>
   <body>
      <div class="event-content">
         <%= render "form", event: @event, event_info: @event_info %>
         <div class="button-wrapper">
            <%= link_to "Back to Home", home_path, class: "gradient-btn" %>
         </div>
      </div>
   </body>